import type { LucideIcon } from "lucide-react";
import {
  Activity,
  BarChart3,
  Building2,
  Camera,
  Check,
  ClipboardList,
  Clock,
  Cpu,
  Factory,
  FileWarning,
  HardHat,
  Headphones,
  HeartHandshake,
  Home,
  KeyRound,
  Landmark,
  Lightbulb,
  Lock,
  MapPin,
  MapPinned,
  PartyPopper,
  Radio,
  Scale,
  School,
  ScrollText,
  Shield,
  ShieldAlert,
  ShieldCheck,
  ShoppingBag,
  Smartphone,
  Target,
  Truck,
  Users,
  Warehouse,
  Zap,
} from "lucide-react";
import type { IconKey } from "@/lib/content/schema";

export const iconMap: Record<IconKey, LucideIcon> = {
  clock: Clock,
  radio: Radio,
  shieldCheck: ShieldCheck,
  mapPin: MapPin,
  users: Users,
  cpu: Cpu,
  shield: Shield,
  headphones: Headphones,
  zap: Zap,
  barChart3: BarChart3,
  building2: Building2,
  shoppingBag: ShoppingBag,
  landmark: Landmark,
  hardHat: HardHat,
  truck: Truck,
  school: School,
  warehouse: Warehouse,
  partyPopper: PartyPopper,
  activity: Activity,
  shieldAlert: ShieldAlert,
  scrollText: ScrollText,
  camera: Camera,
  mapPinned: MapPinned,
  smartphone: Smartphone,
  fileWarning: FileWarning,
  lock: Lock,
  keyRound: KeyRound,
  clipboardList: ClipboardList,
  scale: Scale,
  target: Target,
  heartHandshake: HeartHandshake,
  lightbulb: Lightbulb,
  home: Home,
  factory: Factory,
  check: Check,
};

export function getIcon(key: IconKey): LucideIcon {
  return iconMap[key] ?? Shield;
}
