/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    services: Service;
    testimonials: Testimonial;
    insights: Insight;
    'client-logos': ClientLogo;
    'value-props': ValueProp;
    metrics: Metric;
    'control-centre-steps': ControlCentreStep;
    industries: Industry;
    'contact-submissions': ContactSubmission;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    insights: InsightsSelect<false> | InsightsSelect<true>;
    'client-logos': ClientLogosSelect<false> | ClientLogosSelect<true>;
    'value-props': ValuePropsSelect<false> | ValuePropsSelect<true>;
    metrics: MetricsSelect<false> | MetricsSelect<true>;
    'control-centre-steps': ControlCentreStepsSelect<false> | ControlCentreStepsSelect<true>;
    industries: IndustriesSelect<false> | IndustriesSelect<true>;
    'contact-submissions': ContactSubmissionsSelect<false> | ContactSubmissionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    'home-page': HomePage;
    'solutions-page': SolutionsPage;
    'industries-page': IndustriesPage;
    'control-centre-page': ControlCentrePage;
    'company-page': CompanyPage;
    'technology-page': TechnologyPage;
    'contact-page': ContactPage;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
    'solutions-page': SolutionsPageSelect<false> | SolutionsPageSelect<true>;
    'industries-page': IndustriesPageSelect<false> | IndustriesPageSelect<true>;
    'control-centre-page': ControlCentrePageSelect<false> | ControlCentrePageSelect<true>;
    'company-page': CompanyPageSelect<false> | CompanyPageSelect<true>;
    'technology-page': TechnologyPageSelect<false> | TechnologyPageSelect<true>;
    'contact-page': ContactPageSelect<false> | ContactPageSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  title: string;
  /**
   * URL-safe identifier, e.g. "business-security"
   */
  slug: string;
  category: 'home' | 'business' | 'industrial' | 'specialised';
  description: string;
  theme:
    | 'guards'
    | 'cctv'
    | 'controlRoom'
    | 'dispatch'
    | 'response'
    | 'accessControl'
    | 'industrial'
    | 'residential'
    | 'business'
    | 'events'
    | 'schools'
    | 'government'
    | 'logistics';
  items?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  image?: (number | null) | Media;
  published?: boolean | null;
  /**
   * Lower numbers appear first.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  quote: string;
  author: string;
  org: string;
  published?: boolean | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "insights".
 */
export interface ClientLogo {
  id: number;
  name: string;
  logo?: (number | null) | Media;
  published?: boolean | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "insights".
 */
export interface Insight {
  id: number;
  title: string;
  slug: string;
  contentType: 'article' | 'case-study';
  excerpt: string;
  caseStudy?: {
    problem: string;
    approach: string;
    metrics?:
      | {
          label: string;
          value: string;
          id?: string | null;
        }[]
      | null;
  };
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  published?: boolean | null;
  publishedAt?: string | null;
  heroImage?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "value-props".
 */
export interface ValueProp {
  id: number;
  title: string;
  body: string;
  icon:
    | 'clock'
    | 'radio'
    | 'shieldCheck'
    | 'mapPin'
    | 'users'
    | 'cpu'
    | 'shield'
    | 'headphones'
    | 'zap'
    | 'barChart3'
    | 'building2'
    | 'shoppingBag'
    | 'landmark'
    | 'hardHat'
    | 'truck'
    | 'school'
    | 'warehouse'
    | 'partyPopper'
    | 'activity'
    | 'shieldAlert'
    | 'scrollText'
    | 'camera'
    | 'mapPinned'
    | 'smartphone'
    | 'fileWarning'
    | 'lock'
    | 'keyRound'
    | 'clipboardList'
    | 'scale'
    | 'target'
    | 'heartHandshake'
    | 'lightbulb'
    | 'home'
    | 'factory'
    | 'check';
  /**
   * Renders as the large card when true.
   */
  featured?: boolean | null;
  published?: boolean | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "metrics".
 */
export interface Metric {
  id: number;
  label: string;
  /**
   * Display value, e.g. < 8 min or 42
   */
  value: string;
  suffix?: string | null;
  prefix?: string | null;
  note?: string | null;
  /**
   * Optional number for count-up animations.
   */
  numericValue?: number | null;
  published?: boolean | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "control-centre-steps".
 */
export interface ControlCentreStep {
  id: number;
  title: string;
  body: string;
  icon:
    | 'clock'
    | 'radio'
    | 'shieldCheck'
    | 'mapPin'
    | 'users'
    | 'cpu'
    | 'shield'
    | 'headphones'
    | 'zap'
    | 'barChart3'
    | 'building2'
    | 'shoppingBag'
    | 'landmark'
    | 'hardHat'
    | 'truck'
    | 'school'
    | 'warehouse'
    | 'partyPopper'
    | 'activity'
    | 'shieldAlert'
    | 'scrollText'
    | 'camera'
    | 'mapPinned'
    | 'smartphone'
    | 'fileWarning'
    | 'lock'
    | 'keyRound'
    | 'clipboardList'
    | 'scale'
    | 'target'
    | 'heartHandshake'
    | 'lightbulb'
    | 'home'
    | 'factory'
    | 'check';
  published?: boolean | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "industries".
 */
export interface Industry {
  id: number;
  title: string;
  blurb: string;
  icon:
    | 'clock'
    | 'radio'
    | 'shieldCheck'
    | 'mapPin'
    | 'users'
    | 'cpu'
    | 'shield'
    | 'headphones'
    | 'zap'
    | 'barChart3'
    | 'building2'
    | 'shoppingBag'
    | 'landmark'
    | 'hardHat'
    | 'truck'
    | 'school'
    | 'warehouse'
    | 'partyPopper'
    | 'activity'
    | 'shieldAlert'
    | 'scrollText'
    | 'camera'
    | 'mapPinned'
    | 'smartphone'
    | 'fileWarning'
    | 'lock'
    | 'keyRound'
    | 'clipboardList'
    | 'scale'
    | 'target'
    | 'heartHandshake'
    | 'lightbulb'
    | 'home'
    | 'factory'
    | 'check';
  image?: (number | null) | Media;
  published?: boolean | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions".
 */
export interface ContactSubmission {
  id: number;
  leadType?: ('contact' | 'assessment') | null;
  name: string;
  phone: string;
  email: string;
  service: string;
  message: string;
  siteType?: string | null;
  siteSize?: string | null;
  urgency?: string | null;
  servicesNeeded?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  sourceIp?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'insights';
        value: number | Insight;
      } | null)
    | ({
        relationTo: 'value-props';
        value: number | ValueProp;
      } | null)
    | ({
        relationTo: 'metrics';
        value: number | Metric;
      } | null)
    | ({
        relationTo: 'control-centre-steps';
        value: number | ControlCentreStep;
      } | null)
    | ({
        relationTo: 'industries';
        value: number | Industry;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  category?: T;
  description?: T;
  theme?: T;
  items?:
    | T
    | {
        text?: T;
        id?: T;
      };
  image?: T;
  published?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  quote?: T;
  author?: T;
  org?: T;
  published?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "insights_select".
 */
export interface InsightsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  contentType?: T;
  excerpt?: T;
  caseStudy?:
    | T
    | {
        problem?: T;
        approach?: T;
        metrics?:
          | T
          | {
              label?: T;
              value?: T;
              id?: T;
            };
      };
  content?: T;
  published?: T;
  publishedAt?: T;
  heroImage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "client-logos_select".
 */
export interface ClientLogosSelect<T extends boolean = true> {
  name?: T;
  logo?: T;
  published?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "value-props_select".
 */
export interface ValuePropsSelect<T extends boolean = true> {
  title?: T;
  body?: T;
  icon?: T;
  featured?: T;
  published?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "metrics_select".
 */
export interface MetricsSelect<T extends boolean = true> {
  label?: T;
  value?: T;
  suffix?: T;
  prefix?: T;
  note?: T;
  numericValue?: T;
  published?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "control-centre-steps_select".
 */
export interface ControlCentreStepsSelect<T extends boolean = true> {
  title?: T;
  body?: T;
  icon?: T;
  published?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "industries_select".
 */
export interface IndustriesSelect<T extends boolean = true> {
  title?: T;
  blurb?: T;
  icon?: T;
  image?: T;
  published?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions_select".
 */
export interface ContactSubmissionsSelect<T extends boolean = true> {
  leadType?: T;
  name?: T;
  phone?: T;
  email?: T;
  service?: T;
  message?: T;
  siteType?: T;
  siteSize?: T;
  urgency?: T;
  servicesNeeded?: T;
  sourceIp?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  name: string;
  tagline: string;
  description: string;
  email: string;
  officeHours: string;
  /**
   * E.164 or raw digits for tel: links
   */
  salesPhone: string;
  salesPhoneDisplay: string;
  emergencyPhone: string;
  emergencyPhoneDisplay: string;
  addressFull: string;
  logo?: (number | null) | Media;
  logoMarkText?: string | null;
  seoTitle?: string | null;
  seoDescription?: string | null;
  ogImage?: (number | null) | Media;
  twitterHandle?: string | null;
  robotsNoIndex?: boolean | null;
  certificationsHeading?: string | null;
  certifications?:
    | {
        title: string;
        body: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: number;
  heroSlides?:
    | {
        id: string;
        eyebrow: string;
        title: string;
        body: string;
        theme:
          | 'guards'
          | 'cctv'
          | 'controlRoom'
          | 'dispatch'
          | 'response'
          | 'accessControl'
          | 'industrial'
          | 'residential'
          | 'business'
          | 'events'
          | 'schools'
          | 'government'
          | 'logistics';
        /**
         * Stable id for image placeholder generation
         */
        seed: string;
        image?: (number | null) | Media;
        imageUrl?: string | null;
        ctaPrimary: {
          href: string;
          label: string;
        };
        ctaSecondary: {
          href: string;
          label: string;
        };
      }[]
    | null;
  trustBadges?:
    | {
        icon:
          | 'clock'
          | 'radio'
          | 'shieldCheck'
          | 'mapPin'
          | 'users'
          | 'cpu'
          | 'shield'
          | 'headphones'
          | 'zap'
          | 'barChart3'
          | 'building2'
          | 'shoppingBag'
          | 'landmark'
          | 'hardHat'
          | 'truck'
          | 'school'
          | 'warehouse'
          | 'partyPopper'
          | 'activity'
          | 'shieldAlert'
          | 'scrollText'
          | 'camera'
          | 'mapPinned'
          | 'smartphone'
          | 'fileWarning'
          | 'lock'
          | 'keyRound'
          | 'clipboardList'
          | 'scale'
          | 'target'
          | 'heartHandshake'
          | 'lightbulb'
          | 'home'
          | 'factory'
          | 'check';
        label: string;
        id?: string | null;
      }[]
    | null;
  coreServices: {
    heading: string;
    intro: string;
  };
  controlCentrePreview: {
    heading: string;
    intro: string;
    ctaHref: string;
    ctaLabel: string;
  };
  whyChoose: {
    heading: string;
    intro: string;
  };
  kpisSection: {
    heading: string;
    intro: string;
  };
  testimonialsSection: {
    heading: string;
    intro: string;
  };
  contactCta: {
    heading: string;
    intro: string;
    primaryCta: {
      href: string;
      label: string;
    };
    secondaryCta: {
      href: string;
      label: string;
    };
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
type PageIcon = Industry['icon'];
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "solutions-page".
 */
export interface SolutionsPage {
  id: number;
  title: string;
  intro: string;
  footerHeading: string;
  footerIntro: string;
  footerCtaLabel: string;
  footerCtaHref: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "industries-page".
 */
export interface IndustriesPage {
  id: number;
  title: string;
  intro: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "control-centre-page".
 */
export interface ControlCentrePage {
  id: number;
  heroTitle: string;
  heroIntro: string;
  features?:
    | {
        title: string;
        body: string;
        icon: PageIcon;
        id?: string | null;
      }[]
    | null;
  ctaLabel: string;
  ctaHref: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "company-page".
 */
export interface CompanyPage {
  id: number;
  title: string;
  mission: {
    eyebrow?: string | null;
    title: string;
    body: string;
  };
  vision: {
    eyebrow?: string | null;
    title: string;
    body: string;
  };
  valuesHeading: string;
  values?:
    | {
        title: string;
        body: string;
        icon: PageIcon;
        id?: string | null;
      }[]
    | null;
  compliance: {
    title: string;
    body: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "technology-page".
 */
export interface TechnologyPage {
  id: number;
  title: string;
  intro: string;
  stack?:
    | {
        title: string;
        body: string;
        icon: PageIcon;
        badge?: string | null;
        id?: string | null;
      }[]
    | null;
  dataSecurityHeading: string;
  dataSecurity?:
    | {
        title: string;
        body: string;
        icon: PageIcon;
        id?: string | null;
      }[]
    | null;
  ctaLabel: string;
  ctaHref: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page".
 */
export interface ContactPage {
  id: number;
  title: string;
  intro: string;
  formHeading: string;
  formIntro: string;
  emergencyHeading: string;
  emergencyNote: string;
  officeHeading: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  name?: T;
  tagline?: T;
  description?: T;
  email?: T;
  officeHours?: T;
  salesPhone?: T;
  salesPhoneDisplay?: T;
  emergencyPhone?: T;
  emergencyPhoneDisplay?: T;
  addressFull?: T;
  logo?: T;
  logoMarkText?: T;
  seoTitle?: T;
  seoDescription?: T;
  ogImage?: T;
  twitterHandle?: T;
  robotsNoIndex?: T;
  certificationsHeading?: T;
  certifications?:
    | T
    | {
        title?: T;
        body?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  heroSlides?:
    | T
    | {
        id?: T;
        eyebrow?: T;
        title?: T;
        body?: T;
        theme?: T;
        seed?: T;
        image?: T;
        ctaPrimary?:
          | T
          | {
              href?: T;
              label?: T;
            };
        ctaSecondary?:
          | T
          | {
              href?: T;
              label?: T;
            };
      };
  trustBadges?:
    | T
    | {
        icon?: T;
        label?: T;
        id?: T;
      };
  coreServices?:
    | T
    | {
        heading?: T;
        intro?: T;
      };
  controlCentrePreview?:
    | T
    | {
        heading?: T;
        intro?: T;
        ctaHref?: T;
        ctaLabel?: T;
      };
  whyChoose?:
    | T
    | {
        heading?: T;
        intro?: T;
      };
  kpisSection?:
    | T
    | {
        heading?: T;
        intro?: T;
      };
  testimonialsSection?:
    | T
    | {
        heading?: T;
        intro?: T;
      };
  contactCta?:
    | T
    | {
        heading?: T;
        intro?: T;
        primaryCta?:
          | T
          | {
              href?: T;
              label?: T;
            };
        secondaryCta?:
          | T
          | {
              href?: T;
              label?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
export interface SolutionsPageSelect<T extends boolean = true> {
  title?: T;
  intro?: T;
  footerHeading?: T;
  footerIntro?: T;
  footerCtaLabel?: T;
  footerCtaHref?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
export interface IndustriesPageSelect<T extends boolean = true> {
  title?: T;
  intro?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
export interface ControlCentrePageSelect<T extends boolean = true> {
  heroTitle?: T;
  heroIntro?: T;
  features?:
    | T
    | {
        title?: T;
        body?: T;
        icon?: T;
        id?: T;
      };
  ctaLabel?: T;
  ctaHref?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
export interface CompanyPageSelect<T extends boolean = true> {
  title?: T;
  mission?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        body?: T;
      };
  vision?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        body?: T;
      };
  valuesHeading?: T;
  values?:
    | T
    | {
        title?: T;
        body?: T;
        icon?: T;
        id?: T;
      };
  compliance?:
    | T
    | {
        title?: T;
        body?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
export interface TechnologyPageSelect<T extends boolean = true> {
  title?: T;
  intro?: T;
  stack?:
    | T
    | {
        title?: T;
        body?: T;
        icon?: T;
        badge?: T;
        id?: T;
      };
  dataSecurityHeading?: T;
  dataSecurity?:
    | T
    | {
        title?: T;
        body?: T;
        icon?: T;
        id?: T;
      };
  ctaLabel?: T;
  ctaHref?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
export interface ContactPageSelect<T extends boolean = true> {
  title?: T;
  intro?: T;
  formHeading?: T;
  formIntro?: T;
  emergencyHeading?: T;
  emergencyNote?: T;
  officeHeading?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}