/** Matches `lib/content/schema` enums for Payload select fields. */
export const imageThemeOptions = [
  { label: "Guards", value: "guards" },
  { label: "CCTV", value: "cctv" },
  { label: "Control room", value: "controlRoom" },
  { label: "Dispatch", value: "dispatch" },
  { label: "Response", value: "response" },
  { label: "Access control", value: "accessControl" },
  { label: "Industrial", value: "industrial" },
  { label: "Residential", value: "residential" },
  { label: "Business", value: "business" },
  { label: "Events", value: "events" },
  { label: "Schools", value: "schools" },
  { label: "Government", value: "government" },
  { label: "Logistics", value: "logistics" },
];

export const iconKeyOptions = [
  { label: "Clock", value: "clock" },
  { label: "Radio", value: "radio" },
  { label: "Shield check", value: "shieldCheck" },
  { label: "Map pin", value: "mapPin" },
  { label: "Users", value: "users" },
  { label: "CPU", value: "cpu" },
  { label: "Shield", value: "shield" },
  { label: "Headphones", value: "headphones" },
  { label: "Zap", value: "zap" },
  { label: "Bar chart", value: "barChart3" },
  { label: "Building", value: "building2" },
  { label: "Shopping bag", value: "shoppingBag" },
  { label: "Landmark", value: "landmark" },
  { label: "Hard hat", value: "hardHat" },
  { label: "Truck", value: "truck" },
  { label: "School", value: "school" },
  { label: "Warehouse", value: "warehouse" },
  { label: "Party popper", value: "partyPopper" },
  { label: "Activity", value: "activity" },
  { label: "Shield alert", value: "shieldAlert" },
  { label: "Scroll text", value: "scrollText" },
  { label: "Camera", value: "camera" },
  { label: "Map pinned", value: "mapPinned" },
  { label: "Smartphone", value: "smartphone" },
  { label: "File warning", value: "fileWarning" },
  { label: "Lock", value: "lock" },
  { label: "Key round", value: "keyRound" },
  { label: "Clipboard", value: "clipboardList" },
  { label: "Scale", value: "scale" },
  { label: "Target", value: "target" },
  { label: "Handshake", value: "heartHandshake" },
  { label: "Lightbulb", value: "lightbulb" },
  { label: "Home", value: "home" },
  { label: "Factory", value: "factory" },
  { label: "Check", value: "check" },
];
